### PR TITLE
hu.json

### PR DESCRIPTION
**Pull request by Ninja112**
I transalated some more lines, line 761 is the next.

### CODE REVIEW

**Comment by NikoGrano** [comment]
You could translate them all and then make a pull request....?

**Comment by Ninja112** [comment]
I don't know all the games, and the words of the games. And the games are not at all transalated correctly to hungarian.... (Fast an example: Tribal Wars, transalate to Hungarian: Törcsek Háborúja, game name in Hungarian: Klánháború, which is Clan Wars in English). I play just WOT, so if I finish the WOT part, than I will make a pull request.. .

-- Eredeti üzenet --
Feladó: Niko&lt;notifications@github.com&gt;Címzett: karellodewijk/wottactics&lt;wottactics@noreply.github.com&gt;Elküldve: 2017. szeptember 12. 6:26Tárgy : Re: [karellodewijk/wottactics] hu.json (#14)


You could translate them all and then make a pull request....?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  






_________________________________________

Citromail.hu levelezőrendszerből küldve

Lépj be vagy regisztrálj

**Comment by NikoGrano** [comment]
I guess Tribal Wars is name of that game and it's not supposed to be translated.

**Comment by Ninja112** [comment]
I wrote just an example, there are a lot of games which are transalated like that to Hungarian, and items/thing in the games.

-- Eredeti üzenet --
Feladó: Niko&lt;notifications@github.com&gt;Címzett: karellodewijk/wottactics&lt;wottactics@noreply.github.com&gt;Elküldve: 2017. szeptember 12. 18:26Tárgy : Re: [karellodewijk/wottactics] hu.json (#14)


I guess Tribal Wars is name of that game and it's not supposed to be translated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  






_________________________________________

Citromail.hu levelezőrendszerből küldve

Lépj be vagy regisztrálj

**Comment by karellodewijk** [comment]
Not all games will have localized names or localized map names. If in doubt, I'd leave it in English., but I leave it up to you as you're more familiar with the Hungarian community, no doubt :).

Anyway thanks for the help again.

**Comment by Ninja112** [comment]
I will ask some friends about it, maybe they play the game... If not, than I leave it in English.

-- Eredeti üzenet --
Feladó: karellodewijk&lt;notifications@github.com&gt;Címzett: karellodewijk/wottactics&lt;wottactics@noreply.github.com&gt;Elküldve: 2017. szeptember 12. 21:13Tárgy : Re: [karellodewijk/wottactics] hu.json (#14)


Not all games will have localized names or localized map names. If in doubt, I'd leave it in English., but I leave it up to you as you're more familiar with the Hungarian community, no doubt :).
Anyway thanks for the help again .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  






_________________________________________

Citromail.hu levelezőrendszerből küldve

Lépj be vagy regisztrálj

**Pull request merged**
